function CFD2 = import_normative_data_CFD(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  CFD2 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  CFD2 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  CFD2 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  CFD2 = importfile("C:\Users\juliana.sporrer\Documents\emotion_regulation\CFD Version 2.0.3\CFD 2.0.3 Norming Data and Codebook.xlsx", "CFD 2.0.3 Norming Data", [6, 602]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Feb-2020 10:22:20

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [6, 602];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 69);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":BQ" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Target", "Race", "Gender", "Age", "NumberofRaters", "Female_prop", "Male_prop", "Asian_prop", "Black_prop", "Latino_prop", "Multi_prop", "Other_prop", "White_prop", "Afraid", "Angry", "Attractive", "Babyface", "Disgusted", "Dominant", "Feminine", "Happy", "Masculine", "Prototypic", "Sad", "Suitability", "Surprised", "Threatening", "Trustworthy", "Unusual", "Luminance_median", "Nose_Width", "Nose_Length", "Lip_Thickness", "Face_Length", "R_Eye_H", "L_Eye_H", "Avg_Eye_Height", "R_Eye_W", "L_Eye_W", "Avg_Eye_Width", "Face_Width_Cheeks", "Face_Width_Mouth", "Forehead", "Pupil_Top_R", "Pupil_Top_L", "Asymmetry_pupil_top", "Pupil_Lip_R", "Pupil_Lip_L", "Asymmetry_pupil_lip", "BottomLip_Chin", "Midcheek_Chin_R", "Midcheek_Chin_L", "Cheeks_avg", "Midbrow_Hairline_R", "Midbrow_Hairline_L", "Faceshape", "Heartshapeness", "Noseshape", "LipFullness", "EyeShape", "EyeSize", "UpperHeadLength", "MidfaceLength", "ChinLength", "ForeheadHeight", "CheekboneHeight", "CheekboneProminence", "FaceRoundness", "fWHR"];
opts.VariableTypes = ["string", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Target", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Target", "Race", "Gender", "Suitability"], "EmptyFieldRule", "auto");

% Import the data
CFD2 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":BQ" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    CFD2 = [CFD2; tb]; %#ok<AGROW>
end

end