function tableEmojoined20200526172958 = importfileServerAws(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   TABLEEMOJOINED20200526172958 = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   TABLEEMOJOINED20200526172958 = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   tableEmojoined20200526172958 = importfile('tableEmo_joined_2020-05-26_17-29-58.csv', 1, 1284);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/05/26 17:37:17

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,5,6,11,13,14,16,17,18,19,20,21,22,23,24,26,27,29]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,5,6,11,13,14,16,17,18,19,20,21,22,23,24,26,27,29]);
rawStringColumns = string(raw(:, [2,3,4,7,8,9,10,12,15,25,28,30]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [9,10]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
tableEmojoined20200526172958 = table;
tableEmojoined20200526172958.runID = cell2mat(rawNumericColumns(:, 1));
tableEmojoined20200526172958.startTime = rawStringColumns(:, 1);
tableEmojoined20200526172958.doneTime = rawStringColumns(:, 2);
tableEmojoined20200526172958.participant_participantID = rawStringColumns(:, 3);
tableEmojoined20200526172958.taskSession_taskSessionID = cell2mat(rawNumericColumns(:, 2));
tableEmojoined20200526172958.taskSessionID = cell2mat(rawNumericColumns(:, 3));
tableEmojoined20200526172958.sessionName = rawStringColumns(:, 4);
tableEmojoined20200526172958.openingTime = rawStringColumns(:, 5);
tableEmojoined20200526172958.closingTime = rawStringColumns(:, 6);
tableEmojoined20200526172958.task_taskID = rawStringColumns(:, 7);
tableEmojoined20200526172958.rt = cell2mat(rawNumericColumns(:, 4));
tableEmojoined20200526172958.stimulus = rawStringColumns(:, 8);
tableEmojoined20200526172958.responses = cell2mat(rawNumericColumns(:, 5));
tableEmojoined20200526172958.key_press = cell2mat(rawNumericColumns(:, 6));
tableEmojoined20200526172958.test_part = categorical(rawStringColumns(:, 9));
tableEmojoined20200526172958.blockNb = cell2mat(rawNumericColumns(:, 7));
tableEmojoined20200526172958.trialNb = cell2mat(rawNumericColumns(:, 8));
tableEmojoined20200526172958.condiEmoBlock = cell2mat(rawNumericColumns(:, 9));
tableEmojoined20200526172958.condiEmoTrial = cell2mat(rawNumericColumns(:, 10));
tableEmojoined20200526172958.condiRwd = cell2mat(rawNumericColumns(:, 11));
tableEmojoined20200526172958.posCritDist = cell2mat(rawNumericColumns(:, 12));
tableEmojoined20200526172958.distractor = cell2mat(rawNumericColumns(:, 13));
tableEmojoined20200526172958.posTarget = cell2mat(rawNumericColumns(:, 14));
tableEmojoined20200526172958.target = cell2mat(rawNumericColumns(:, 15));
tableEmojoined20200526172958.trial_type = categorical(rawStringColumns(:, 10));
tableEmojoined20200526172958.trial_index = cell2mat(rawNumericColumns(:, 16));
tableEmojoined20200526172958.time_elapsed = cell2mat(rawNumericColumns(:, 17));
tableEmojoined20200526172958.internal_node_id = rawStringColumns(:, 11);
tableEmojoined20200526172958.run_id = cell2mat(rawNumericColumns(:, 18));
tableEmojoined20200526172958.date = rawStringColumns(:, 12);

